### ISSUE TITLE
TypeError: this._getEventHandlerFor is not a function

### ISSUE THREAD

**Issue by jdnichollsc** [enzymejs/enzyme#2436]
### Current behavior

- Configuration:
```js
const { JSDOM } = require('jsdom')

const jsdom = new JSDOM()
const { window } = jsdom

function copyProps (src, target) {
  const props = Object.getOwnPropertyNames(src)
    .filter(prop => typeof target[prop] === 'undefined')
    .map(prop => Object.getOwnPropertyDescriptor(src, prop))
  Object.defineProperties(target, props)
}

class XMLHttpRequest {}
global.XMLHttpRequest = XMLHttpRequest
global.fetch = require('jest-fetch-mock')
global.window = window
global.document = window.document
global.navigator = {
  userAgent: 'node.js'
}
copyProps(window, global)

// Setup adapter to work with enzyme 3.2.0
const Enzyme = require('enzyme')
const Adapter = require('enzyme-adapter-react-16')

Enzyme.configure({ adapter: new Adapter() })

// Ignore React Web errors when using React Native
const realError = console.error
console.error = (...x) => {
  if (x[0].startsWith('Warning:')) {
    return
  }
  realError(...x)
}
```

- Log of the issue:
```
  ● Test suite failed to run

    TypeError: this._getEventHandlerFor is not a function

      at Object.get (node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:86:26)
          at Array.forEach (<anonymous>)

Test Suites: 1 failed, 1 total
```

### Expected behavior

Don't report issues of jsdom 👍 

#### Version

| library             | version
| ------------------- | -------
| enzyme              | ^3.4.1
| react               | 16.10.2
| react-dom           | ^16.10.2
| react-test-renderer | ^16.9.0
| adapter (below)     | ^1.2.0

#### Adapter

- [x] enzyme-adapter-react-16

Thanks for your help!

**Comment by ljharb** [comment]
You're using a quite old version of enzyme *and* the adapter - what happens if you upgrade them to the latest?

**Comment by jdnichollsc** [comment]
Oh it looks like it's fixed using the new configuration for copy props, thanks!
